### ISSUE TITLE
ch6 最小限のテストをデプロイする

### ISSUE THREAD

**Issue by tkeydll** [tkeydll/fastify-webapp-sample#2]

**Comment by tkeydll** [comment]
`npx codeceptjs shell` でコマンドを終了しても cli-history が出力されない。

**Comment by tkeydll** [comment]
> `npx codeceptjs shell` でコマンドを終了しても cli-history が出力されない。

これも本質ではないので無視して続行。smoke_test.js にコマンドを直接書いて実行。
ログインするとデバッグ実行しているアプリがクラッシュする。

**Comment by tkeydll** [comment]
```
Server listening at http://[::1]:80
node:_http_server:342
    throw new ERR_HTTP_HEADERS_SENT('write');
    ^

Error [ERR_HTTP_HEADERS_SENT]: Cannot write headers after they are sent to the client
    at ServerResponse.writeHead (node:_http_server:342:11)
    at onSendEnd (C:\Users\tkeyd\git\fastify-webapp-sample\node_modules\fastify\lib\reply.js:571:9)
    at wrapOnSendEnd (C:\Users\tkeyd\git\fastify-webapp-sample\node_modules\fastify\lib\reply.js:537:5)
    at next (C:\Users\tkeyd\git\fastify-webapp-sample\node_modules\fastify\lib\hooks.js:213:7)
    at C:\Users\tkeyd\git\fastify-webapp-sample\node_modules\@fastify\session\lib\fastifySession.js:190:9
    at C:\Users\tkeyd\git\fastify-webapp-sample\node_modules\@fastify\session\lib\session.js:171:9
    at C:\Users\tkeyd\git\fastify-webapp-sample\node_modules\connect-pg-simple\index.js:396:24
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  code: 'ERR_HTTP_HEADERS_SENT'
}
```

postgres に接続できてない？

**Comment by tkeydll** [comment]
> postgres に接続できてない？

全然ちがった。レスポンスが2度送信されているのが原因。Copilotちゃんに直してもらう。

```js
  server.post(
    "/login",
    {
      preValidation: passport.authenticate("local", {
        //successRedirect: "/items",
        authInfo: false,
      }),
    },
    async (request, reply) => {
      if (request.isAuthenticated()) {
        return reply.redirect("/items");
      } else {
        return reply.redirect("/login");
      }
    }
  );
```

**Comment by tkeydll** [comment]
`npm run test` が動かない。

ちょいちょい罠があるな。。
